@baseUrl = http://localhost:7071/api

###
#
POST {{baseUrl}}/SetCommonStaticClassValue

123

###
#
GET {{baseUrl}}/GetCommonStaticClassValue

###
#
GET {{baseUrl}}/UseSomeService

###
#
GET {{baseUrl}}/UseSomeService

###
#
GET {{baseUrl}}/GetSomeOptionValue

###
#
POST {{baseUrl}}/LogWithSerilog

{
    "text": "some-text",
    "number": 32
}
